# Generated by Django 3.2.5 on 2021-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thel_shop', '0002_clothes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
