# Generated by Django 3.2.3 on 2021-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='abstract',
        ),
        migrations.AddField(
            model_name='news',
            name='URI',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='abstract_in_another_language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='another_title',
            field=models.CharField(default='default ', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='bibliographic_entry',
            field=models.TextField(blank=True),
        ),
    ]
