# Generated by Django 3.2.3 on 2021-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_uri_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.TextField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
