# Generated by Django 3.2.3 on 2021-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
