# Generated by Django 3.2.3 on 2021-06-13 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('news_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.news', verbose_name='Новость')),
            ],
        ),
    ]
