# Generated by Django 3.2.3 on 2021-06-15 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0012_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(related_name='news_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
